COMMENT ON TABLE ACCOUNT IS 'Maintains the account primary key.' ; 
COMMENT ON TABLE ACCOUNTGROUP IS 'Also known as Customer Group, this defines the groups available in the system.' ; 
COMMENT ON TABLE ACCOUNTGROUPRELATION IS 'Defines the Account(Customer & Vendor) to Group relationship.  Allows for many groups to associate with one Account.' ; 
COMMENT ON TABLE ACCOUNTTYPE IS 'Unknown' ; 
COMMENT ON TABLE ADDRESS IS 'Maintains a list of pre-defined addresses for Accounts(Customer & Vendor).' ; 
COMMENT ON TABLE ADDRESSTYPE IS 'Reference table for address types.' ; 
COMMENT ON TABLE ASACCOUNT IS 'Table of QuickBooks General Ledger Accounts' ; 
COMMENT ON TABLE ASACCOUNTTYPE IS 'Reference table for General Ledger Account types' ; 
COMMENT ON TABLE ASSOCPRICE IS 'Unknown' ; 
COMMENT ON TABLE ASSOCPRICETYPE IS 'Reference table for Associated Price Types' ; 
COMMENT ON TABLE BOM IS 'Bill of Material Header table' ; 
COMMENT ON TABLE BOMAUTOCREATETYPE IS 'Reference table for Bill of Material create types' ; 
COMMENT ON TABLE BOMITEM IS 'Bill of Material Detail table' ; 
COMMENT ON TABLE BOMITEMGROUP IS 'Bill of Material Optional Group detail' ; 
COMMENT ON TABLE BOMITEMTOLOCATION IS 'Bill of Material Default Pick Location for Parts' ; 
COMMENT ON TABLE BOMITEMTYPE IS 'Reference table for Bill of Material Item types' ; 
COMMENT ON TABLE BOMTOLOCATION IS 'Bill of Material to Location Mapping' ; 
COMMENT ON TABLE CALCATEGORY IS 'Calendar Category List' ; 
COMMENT ON TABLE CALEVENT IS 'Calendar Events' ; 
COMMENT ON TABLE CARRIER IS 'List of Shipment Carriers' ; 
COMMENT ON TABLE COMPANY IS 'Company Table' ; 
COMMENT ON TABLE CONTACT IS 'Contact Information Table' ; 
COMMENT ON TABLE CONTACTTYPE IS 'Reference of Contact Types' ; 
COMMENT ON TABLE COSTLAYER IS 'FIFO/LIFO Inventory Valuation' ; 
COMMENT ON TABLE COSTLAYERSTATUS IS 'Reference Table of Costlayer Status' ; 
COMMENT ON TABLE COUNTRYCONST IS 'Reference List of Countries' ; 
COMMENT ON TABLE CURRENCY IS 'Reference list of currencies' ; 
COMMENT ON TABLE CUSTOMDECIMAL IS 'Custom Field storage for Decimal Numbers' ; 
COMMENT ON TABLE CUSTOMER IS 'Customer Information Table' ; 
COMMENT ON TABLE CUSTOMERINCLTYPE IS 'Reference list of Pricing Rule Customer Applies To names' ; 
COMMENT ON TABLE CUSTOMERPARTS IS 'Unknown' ; 
COMMENT ON TABLE CUSTOMERSTATUS IS 'Reference list of Customer Statuses' ; 
COMMENT ON TABLE CUSTOMFIELD IS 'Maintains a list of Custom Fields and their Relationship to Modules' ; 
COMMENT ON TABLE CUSTOMFIELDTYPE IS 'Reference list of Custom Field types' ; 
COMMENT ON TABLE CUSTOMINTEGER IS 'Custom Field Storage for Whole Numbers' ; 
COMMENT ON TABLE CUSTOMLIST IS 'Defines a Custom Field List' ; 
COMMENT ON TABLE CUSTOMLISTITEM IS 'Defines a Custom Field List Item (Selection)' ; 
COMMENT ON TABLE CUSTOMSET IS 'Custom Field Storage for List Items' ; 
COMMENT ON TABLE CUSTOMTIMESTAMP IS 'Custom Field Storage For Date Custom Fields' ; 
COMMENT ON TABLE CUSTOMVARCHAR IS 'Custom Field Storage for Text Custom Fields' ; 
COMMENT ON TABLE CUSTOMVARCHARLONG IS 'Custom Field Storage for Long Text Custom Fields' ; 
COMMENT ON TABLE DATABASEVERSION IS 'Maintains a list of when a database is upgraded to' ; 
COMMENT ON TABLE DCOPTIONS IS 'Unknown' ; 
COMMENT ON TABLE DEFAULTLOCATION IS 'Maintains a relationship of Part & Location Group to a SpecifiC Location for Putaway and Receiving.' ; 
COMMENT ON TABLE FBSCHEDULE IS 'Defines the list of Scheduled Tasks.' ; 
COMMENT ON TABLE FBSCHEDULEACTIONTYPE IS 'Reference list of Scheduled Task Action Types' ; 
COMMENT ON TABLE FBSCHEDULEHISTORY IS 'Maintains a list of Scheduled Task Completion History.' ; 
COMMENT ON TABLE FBSCHEDULEREPORTPARAMETER IS 'Defines the optional parameters of Reports when scheduled through the Schedule Module' ; 
COMMENT ON TABLE FOBPOINT IS 'Free on Board (FOB) Point Reference List' ; 
COMMENT ON TABLE INTEGRATEDAPP IS 'Maintains a list of Integrated Apps' ; 
COMMENT ON TABLE INTEGRATEDAPPSTATUS IS 'Defines an Integrated App status' ; 
COMMENT ON TABLE INTEGRATIONPROPERTIES IS 'Unknown'; 
COMMENT ON TABLE INTEGRATIONTYPE IS 'Unknown' ; 
COMMENT ON TABLE INVENTORYLOG IS 'Transactional List of Inventory Movement' ; 
COMMENT ON TABLE INVENTORYLOGTOCOSTLAYER IS 'Maps an Inventory Log Record to FIFO/LIFO Costlayer Record' ; 
COMMENT ON TABLE INVENTORYLOGTYPE IS 'Defines a the Inventory Log Types Allowable' ; 
COMMENT ON TABLE ITEMADJUST IS 'Item Adjust Information' ; 
COMMENT ON TABLE ITEMADJUSTTYPE IS 'Item Adjust Types' ; 
COMMENT ON TABLE KITDISPLAYTYPE IS 'Reference List of Kit Display Options' ; 
COMMENT ON TABLE KITITEM IS 'Items within Kits' ; 
COMMENT ON TABLE KITITEMTYPE IS 'Kit Item Types' ; 
COMMENT ON TABLE KITOPTION IS 'Kit Item Optional Groups' ; 
COMMENT ON TABLE KITTYPE IS 'Kit Types' ; 
COMMENT ON TABLE LGSUMTYPE IS 'Uknown' ; 
COMMENT ON TABLE LOCATION IS 'Inventory Location - aka Shelf/Bin/Aisle' ; 
COMMENT ON TABLE LOCATIONGROUP IS 'Inventory Location Group - Warehouse' ; 
COMMENT ON TABLE LOCATIONTYPE IS 'Location Types' ; 
COMMENT ON TABLE MEMO IS 'Memo Storage Table' ; 
COMMENT ON TABLE MO IS 'Manufacture Order' ; 
COMMENT ON TABLE MODULE IS 'Unknown' ; 
COMMENT ON TABLE MOITEM IS 'Manufacture Order Items' ; 
COMMENT ON TABLE MOITEMSTATUS IS 'Reference list of Manufacture Order Item Status' ; 
COMMENT ON TABLE MOSTATUS IS 'Manufacture Order Status' ; 
COMMENT ON TABLE OBJECTTOOBJECT IS 'Maps Records from One Table to Another' ; 
COMMENT ON TABLE OBJECTTOOBJECTTYPE IS 'Object To Object Type' ; 
COMMENT ON TABLE ORDERHISTORY IS 'Order History' ; 
COMMENT ON TABLE ORDERTYPE IS 'Order Type' ; 
COMMENT ON TABLE PABASEAMOUNTTYPE IS 'Pricing Rule Product Base Amount Type List' ; 
COMMENT ON TABLE PACKAGETYPES IS 'UPS Package Types?' ; 
COMMENT ON TABLE PART IS 'Part Records' ; 
COMMENT ON TABLE PARTCATEGORY IS 'Unknown' ; 
COMMENT ON TABLE PARTCOST IS 'Maintains the Part Average Cost and QTY' ; 
COMMENT ON TABLE PARTREORDER IS 'Maintains the Part Reorder Point and Order Up To Level' ; 
COMMENT ON TABLE PARTTOTRACKING IS 'Maps a part to its part tracking types' ; 
COMMENT ON TABLE PARTTRACKING IS 'Defines Part Tracking, Lot, ExpDate, Serial Number, Revision' ; 
COMMENT ON TABLE PARTTRACKINGTYPE IS 'Reference table for parttracking types, text, number, date, serial' ; 
COMMENT ON TABLE PARTTYPE IS 'Reference table for part types' ; 
COMMENT ON TABLE PATYPE IS 'Reference table for pricing rule types' ; 
COMMENT ON TABLE PAYMENTMETHOD IS 'Maintains a list of payment methods' ; 
COMMENT ON TABLE PAYMENTTERMS IS 'Maintains the Payment Terms used' ; 
COMMENT ON TABLE PAYMENTTERMSTYPE IS 'Reference table for payment term types' ; 
COMMENT ON TABLE PAYMENTTYPE IS 'Unknown' ; 
COMMENT ON TABLE PICK IS 'Pick Record Header' ; 
COMMENT ON TABLE PICKITEM IS 'Pick Item Detail' ; 
COMMENT ON TABLE PICKITEMSTATUS IS 'Reference table for pick item statuses' ; 
COMMENT ON TABLE PICKITEMTYPE IS 'Reference table for pick item types' ; 
COMMENT ON TABLE PICKSTATUS IS 'Reference table for pick item status' ; 
COMMENT ON TABLE PICKTYPE IS 'Reference table for pick types' ; 
COMMENT ON TABLE PO IS 'Purchase Order Header Table' ; 
COMMENT ON TABLE POITEM IS 'Purchase Order Item Detail Table' ; 
COMMENT ON TABLE POITEMSTATUS IS 'Reference tbale for Purchase Order Item Status' ; 
COMMENT ON TABLE POITEMTYPE IS 'Reference table for Purchase Order item Types' ; 
COMMENT ON TABLE POST IS 'Maintains a list of miscalleneous QuickBooks posting records' ; 
COMMENT ON TABLE POSTATUS IS 'Reference table for Purchase Order status' ; 
COMMENT ON TABLE POSTORDERSTATUS IS 'Unknown' ; 
COMMENT ON TABLE POSTPO IS 'Contains header data for Purchase Order transactions to be posted to QuickBooks' ; 
COMMENT ON TABLE POSTPOITEM IS 'Contains detail data for Purchase Order transactions to be posted to QuickBooks' ; 
COMMENT ON TABLE POSTRANSACTION IS 'Point of Sale Payment Records' ; 
COMMENT ON TABLE POSTSO IS 'Contains header data for Sales Order transactions to be posted to QuickBooks' ; 
COMMENT ON TABLE POSTSOITEM IS 'Contains detail data for Sales Order transactions to be posted to QuickBooks' ; 
COMMENT ON TABLE POSTSTATUS IS 'Unknown' ; 
COMMENT ON TABLE POSTTYPE IS 'Unknown' ; 
COMMENT ON TABLE POSTWO IS 'Contains header data for finished Work Order transactions to be posted to QuickBooks' ; 
COMMENT ON TABLE POSTWOITEM IS 'Contains detail data for finished Work Order transactions to be posted to QuickBooks' ; 
COMMENT ON TABLE POSTXO IS 'Unused afaik' ; 
COMMENT ON TABLE POSTXOITEM IS 'Unused afaik' ; 
COMMENT ON TABLE POTYPE IS 'Reference table for Purchase Order Types' ; 
COMMENT ON TABLE PRICINGRULE IS 'Maintains the Pricing Rules used in Fishbowl Inventory' ; 
COMMENT ON TABLE PRIORITY IS 'Sales, Pick - Priority Reference Table' ; 
COMMENT ON TABLE PRODUCT IS 'Product table, also contains kit (header) ' ; 
COMMENT ON TABLE PRODUCTINCLTYPE IS 'Pricing Rule Product Applies to Reference' ; 
COMMENT ON TABLE PRODUCTTOTREE IS 'Maps a Product to a Product Tree folder' ; 
COMMENT ON TABLE PRODUCTTREE IS 'Product Tree' ; 
COMMENT ON TABLE PROPERTYCATEGORY IS 'Unknown' ; 
COMMENT ON TABLE QBCLASS IS 'QuickBooks Classes' ; 
COMMENT ON TABLE QUICKLIST IS 'Sales Order Quicklist item record header' ; 
COMMENT ON TABLE QUICKLISTITEM IS 'QuickList item record detail' ; 
COMMENT ON TABLE RECEIPT IS 'Open Receipt Record Header' ; 
COMMENT ON TABLE RECEIPTITEM IS 'Receipt Item Record Detail' ; 
COMMENT ON TABLE RECEIPTITEMSTATUS IS 'Reference table for Receipt Item Status' ; 
COMMENT ON TABLE RECEIPTITEMTYPE IS 'Reference table for Receipt Item type' ; 
COMMENT ON TABLE RECEIPTSTATUS IS 'Reference table for Receipt Status' ; 
COMMENT ON TABLE RECEIPTTYPE IS 'Reference table for receipt type' ; 
COMMENT ON TABLE REGISTER IS 'Defines the Point of Sale Registers' ; 
COMMENT ON TABLE REPORT IS 'Maintains a list of System and Custom reports' ; 
COMMENT ON TABLE REPORTPARAMETER IS 'Maintains the saved Report optional parameters' ; 
COMMENT ON TABLE REPORTSECURITY IS 'Maps a user group to a report' ; 
COMMENT ON TABLE REPORTTOMODULE IS 'Maps a report to a module' ; 
COMMENT ON TABLE REPORTTREE IS 'The folder organizational structure for reports' ; 
COMMENT ON TABLE RESPONSIBILITY IS 'Not sure' ; 
COMMENT ON TABLE RMA IS 'RMA Module Header' ; 
COMMENT ON TABLE RMAITEM IS 'RMA Module Detail' ; 
COMMENT ON TABLE RMAITEMTYPE IS 'Reference table for RMA item types' ; 
COMMENT ON TABLE RMASTATUS IS 'Reference table for RMA status' ; 
COMMENT ON TABLE RNDTYPE IS 'Reference Table for Pricing Rule Round Type' ; 
COMMENT ON TABLE SERIAL IS 'On Hand Serial Storage' ; 
COMMENT ON TABLE SERIALNUM IS 'On Hand Serial Storage - Exact Field' ; 
COMMENT ON TABLE SHIP IS 'Ship Module Header' ; 
COMMENT ON TABLE SHIPCARTON IS 'Ship Cartons - Contains tracking number, weight, amount etc,.' ; 
COMMENT ON TABLE SHIPITEM IS 'Ship Module Detail' ; 
COMMENT ON TABLE SHIPPINGIMPORT IS 'Temprorary table that supports the supervised update of Ship Carton, UPS, USPS, FedEx uses these' ; 
COMMENT ON TABLE SHIPSTATUS IS 'Reference table for Ship Status' ; 
COMMENT ON TABLE SHIPTERMS IS 'Reference table for Ship Terms' ; 
COMMENT ON TABLE SHIPUPSCARTONDETAILS IS 'UPS Module Ship Carton Details' ; 
COMMENT ON TABLE SHIPUPSDETAILS IS 'UPS Module ?' ; 
COMMENT ON TABLE SO IS 'Sales Order Header' ; 
COMMENT ON TABLE SOITEM IS 'Sales Order Detail' ; 
COMMENT ON TABLE SOITEMSTATUS IS 'Reference for Sales Order Item Status' ; 
COMMENT ON TABLE SOITEMTOMOITEM IS 'Maps a Sales Order Item to A Manufacture Order Item' ; 
COMMENT ON TABLE SOITEMTYPE IS 'Reference for Sales Order Item Type' ; 
COMMENT ON TABLE SOSTATUS IS 'Reference table for Sales Order Status' ; 
COMMENT ON TABLE SOTYPE IS 'Reference table for Sales Order Type' ; 
COMMENT ON TABLE STATECONST IS 'States - Provinces' ; 
COMMENT ON TABLE SYSPROPERTIES IS 'System Properties - Property Module' ; 
COMMENT ON TABLE SYSUSER IS 'System Users - or just users' ; 
COMMENT ON TABLE TABLEREFERENCE IS 'Reference to describe table references in other tables' ; 
COMMENT ON TABLE TAG IS 'Maintains tag records for Inventory and Locations, is Quantity On Hand' ; 
COMMENT ON TABLE TAGTYPE IS 'Reference table for Tag Types' ; 
COMMENT ON TABLE TAXRATE IS 'Tax Rates' ; 
COMMENT ON TABLE TAXRATETYPE IS 'Reference table for Tax Rate Types' ; 
COMMENT ON TABLE TIINVENTORYLOG IS 'Tracking Information for Inventory Log Records - Non Serialized' ; 
COMMENT ON TABLE TIINVENTORYLOGSN IS 'Tracking Information for Inventory Log Records - Serialized' ; 
COMMENT ON TABLE TRACKINGDATE IS 'Part Tracking Information for Date Types' ; 
COMMENT ON TABLE TRACKINGDECIMAL IS 'Part Tracking Information for Decimal Types' ; 
COMMENT ON TABLE TRACKINGINFO IS 'Part Tracking Information to Modules - Non Serialized' ; 
COMMENT ON TABLE TRACKINGINFOSN IS 'Part Tracking Information to Modules - Serialized' ; 
COMMENT ON TABLE TRACKINGINTEGER IS 'Part Tracking Information for Whole Number Types' ; 
COMMENT ON TABLE TRACKINGTEXT IS 'Part Tracking Information for Text Types' ; 
COMMENT ON TABLE UOM IS 'Unit of Measures' ; 
COMMENT ON TABLE UOMCONVERSION IS 'Unit of Measure conversions' ; 
COMMENT ON TABLE UOMTYPE IS 'Unit of Measure Types' ; 
COMMENT ON TABLE UPSACCOUNT IS 'Unknown?' ; 
COMMENT ON TABLE UPSCOD IS 'Unknown?' ; 
COMMENT ON TABLE UPSPAYMENTTYPE IS 'X' ; 
COMMENT ON TABLE UPSRETURNSHIPMENT IS 'X' ; 
COMMENT ON TABLE UPSSERVICES IS 'X' ; 
COMMENT ON TABLE USERACCESS IS 'Unkown' ; 
COMMENT ON TABLE USERGROUP IS 'Defines the User Groups' ; 
COMMENT ON TABLE USERGROUPREL IS 'Defines the User to User Group Relationship' ; 
COMMENT ON TABLE USERLOG IS 'Logs when users log into the system and off' ; 
COMMENT ON TABLE USERPROPERTIES IS 'Unknown' ; 
COMMENT ON TABLE USERTOLG IS 'Specifies which users can access information in Location Groups' ; 
COMMENT ON TABLE VENDOR IS 'Vendors' ; 
COMMENT ON TABLE VENDORCOSTRULE IS 'Vendor Cost Rules' ; 
COMMENT ON TABLE VENDORPARTS IS 'Vendors to Parts Mapping' ; 
COMMENT ON TABLE VENDORSTATUS IS 'Reference table for Vendor Status' ; 
COMMENT ON TABLE WATCH IS 'Unknown' ; 
COMMENT ON TABLE WATCHTYPE IS 'X' ; 
COMMENT ON TABLE WO IS 'Work Order Header' ; 
COMMENT ON TABLE WOASSIGNEDUSERS IS 'The Assign Users to Work Order Table' ; 
COMMENT ON TABLE WOITEM IS 'Work Order Item Detail' ; 
COMMENT ON TABLE WOSTATUS IS 'Reference table for Work Order Statuses' ; 
COMMENT ON TABLE XO IS 'Transfer Order Header' ; 
COMMENT ON TABLE XOITEM IS 'Transfer Order Item Detail' ; 
COMMENT ON TABLE XOITEMSTATUS IS 'Reference table for Transfer Order Item Status' ; 
COMMENT ON TABLE XOITEMTYPE IS 'Reference table for Transfer Order Item Type' ; 
COMMENT ON TABLE XOSTATUS IS 'Reference table for Transfer Order Status' ; 
COMMENT ON TABLE XOTYPE IS 'Reference table for Transfer Order type' ; 
COMMIT;
